"""Constants for TRM Reranker."""

# Special token IDs
PAD_TOKEN_ID = 0
CLS_TOKEN_ID = 101
SEP_TOKEN_ID = 102

# Default hyperparameters
DEFAULT_MAX_LENGTH = 512
DEFAULT_HIDDEN_SIZE = 512
DEFAULT_NUM_LAYERS = 2
DEFAULT_NUM_HEADS = 8
DEFAULT_FFN_EXPANSION = 2

# Training defaults
DEFAULT_LEARNING_RATE = 1e-4
DEFAULT_WEIGHT_DECAY = 0.1
DEFAULT_WARMUP_STEPS = 2000
DEFAULT_BATCH_SIZE = 32

# TRM-specific
DEFAULT_N_SUPERVISION = 16
DEFAULT_H_CYCLES = 3
DEFAULT_L_CYCLES = 6
DEFAULT_HALT_EXPLORATION_PROB = 0.1

# Logging
LOG_EVERY_N_STEPS = 50
VAL_CHECK_INTERVAL = 1.0
